#!/usr/bin/env python3
"""Emit the license facts already in the Dockerfiles as a machine-readable manifest.

Every license error that has reached a public surface so far was a fact copied
by hand out of a Dockerfile and then left behind when the Dockerfile moved on:
GeoCLIP published as Apache-2.0 when upstream is MIT, SAM2 and MOMO published
with half of a composite license, LunarFM recorded as CC-BY-4.0 when it is
PolyForm Strict. A consumer that reads LICENSE_MANIFEST.json instead of reading
a Dockerfile with its eyes cannot drift that way.

This records what the labels say. It does not judge whether they are right —
that is scripts/license_audit.py, which compares them against upstream.

  python3 scripts/license_manifest.py            # regenerate the manifest
  python3 scripts/license_manifest.py --check    # CI: fail if it is stale
"""

import argparse
import json
import re
import sys
from pathlib import Path

MANIFEST_NAME = "LICENSE_MANIFEST.json"

# Comment lines can carry the same key="value" shape as a real label (an
# earlier value left in place above the LABEL block), so they are dropped
# before anything is parsed.
COMMENT_RE = re.compile(r"^[ \t]*#.*$", re.MULTILINE)
CONTINUATION_RE = re.compile(r"\\[ \t]*\r?\n")
LABEL_INSTRUCTION_RE = re.compile(
    r"^[ \t]*LABEL[ \t]+(.*)$", re.IGNORECASE | re.MULTILINE
)
PAIR_RE = re.compile(r'([A-Za-z0-9_.\-]+)="((?:[^"\\]|\\.)*)"')

# Label keys the manifest carries, mapped to their manifest field names. The
# "licence" spelling in the note key is the repo's own; it is matched verbatim
# rather than corrected, because the label is the source of truth here.
FIELDS = {
    "licenses": "org.opencontainers.image.licenses",
    "licence_note": "bradleylab.model.licence.note",
    "status": "bradleylab.model.status",
    "upstream": "bradleylab.model.upstream",
}


def read_labels(dockerfile: Path) -> dict[str, str]:
    """Return every key="value" label declared in a Dockerfile.

    Handles the repo's usual form — one LABEL instruction with backslash
    continuations — and also several separate LABEL instructions. A key
    declared twice takes its last value, matching how Docker resolves it.
    """
    text = COMMENT_RE.sub("", dockerfile.read_text(errors="replace"))
    text = CONTINUATION_RE.sub(" ", text)

    labels: dict[str, str] = {}
    for instruction in LABEL_INSTRUCTION_RE.findall(text):
        for key, value in PAIR_RE.findall(instruction):
            labels[key] = value.replace('\\"', '"').replace("\\\\", "\\")
    return labels


def build_manifest(root: Path) -> dict:
    """Collect the license facts from every top-level <image>/Dockerfile.

    Missing labels stay in the output as null rather than vanishing, so a
    consumer reading a field never has to distinguish "absent" from "the
    manifest is a version that predates this field".
    """
    containers = []
    for dockerfile in sorted(root.glob("*/Dockerfile")):
        labels = read_labels(dockerfile)
        entry = {"name": dockerfile.parent.name}
        entry.update({field: labels.get(key) or None for field, key in FIELDS.items()})
        containers.append(entry)

    return {
        "_comment": (
            "Generated by scripts/license_manifest.py from the Dockerfile labels. "
            "Do not edit by hand — edit the Dockerfile's label and regenerate. "
            "Composite licenses are recorded verbatim; do not split or normalize them."
        ),
        "container_count": len(containers),
        "containers": containers,
    }


def render(manifest: dict) -> str:
    return json.dumps(manifest, indent=2, ensure_ascii=False) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the committed manifest does not match the Dockerfiles",
    )
    args = parser.parse_args()

    root = Path(__file__).resolve().parent.parent
    path = root / MANIFEST_NAME
    manifest = build_manifest(root)
    generated = render(manifest)

    if not args.check:
        path.write_text(generated)
        print(f"Wrote {MANIFEST_NAME} ({manifest['container_count']} containers).")
        return 0

    committed = path.read_text() if path.exists() else ""
    if committed == generated:
        print(f"{MANIFEST_NAME} is up to date.")
        return 0

    print(
        f"{MANIFEST_NAME} does not match the Dockerfile labels.\n"
        "Run `python3 scripts/license_manifest.py` and commit the result.",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    sys.exit(main())
